### ISSUE TITLE
reverse proxy error

### ISSUE THREAD

**Issue by Coll147** [elbowz/mobileMule#10]
I know this has nothing to do with the theme but since I put it up I have problems with my investment proxy made with nginx. Like the bar goes up and down the loading bar but it stays blank and nothing comes out. It should be noted that locally it does work. I'm using the free version.
Below I provide my nginx configuration and some sscreenshots.

`server {
  listen 80;
  server_name ""domain"";
  return 301 https://$server_name$request_uri;
}
server {
  listen 443 ssl http2;

  server_name ""domain"";
  ssl_certificate /etc/letsencrypt/live/""domain""/cert.pem;
  ssl_certificate_key /etc/letsencrypt/live/""domain""/privkey.pem;
  ssl_session_cache shared:SSL:10m;
  ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers  HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers on;

  location / {
    proxy_pass http://localhost:4711/;
    proxy_buffering off;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
`

![Screenshot_2022-07-02-00-42-23-544_com android chrome](https://user-images.githubusercontent.com/91793263/176975098-08f16f1f-9acf-4216-949e-0c2661221e6c.jpg)

![IMG_20220702_003308](https://user-images.githubusercontent.com/91793263/176974916-973aadca-5b29-45e8-a1f4-6e92c1862fc7.jpg)

**Comment by elbowz** [comment]
yes, I think is unrelated to mobileMule, you should search (on Google) about: *nginx, amule and reverse proxy*

Anyway this is my base configuration, and it's works:

```
location /amule/ {
    proxy_pass              http://localhost:4711/;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by Coll147** [comment]
Thanks for the help but it still doesn't work. When I remove the amule theme it works fine without problems but when I put mobilemule the loading bar goes up and down very fast but it doesn't finish loading.

**Comment by Coll147** [comment]
Here I attach the link to my aMule instance so you can check it yourself.
https://mule.collindex.ga

**Comment by elbowz** [comment]
at the posted link I don't see mobileMule template but another one...

Have you try to clean all browser cache?! (eg. chrome://settings/clearBrowserData)

**Comment by Coll147** [comment]
I'm sorry I removed the theme because I needed to download some things but I already put it back sorry xd. I tried clearing the cache but it still doesn't work :_(
![IMG_20220711_110857](https://user-images.githubusercontent.com/91793263/178229877-57f59804-8bce-4f02-ba86-9d4443fc3d76.jpg)
![Screenshot_2022-07-11-11-05-08-599_com android chrome](https://user-images.githubusercontent.com/91793263/178229891-0636066b-b1cc-4897-858a-377d8224b91f.jpg)
![Screenshot_2022-07-11-11-07-16-394_com android chrome](https://user-images.githubusercontent.com/91793263/178229898-e9a2ed12-ffad-4e96-927d-bed3184d591f.jpg)

**Comment by Coll147** [comment]
Wait a minute, I've tried another web browser (Firefox Focus) AND IT WORKS. Damn Chrome lol.
![Screenshot_2022-07-11-11-13-52-284_org mozilla focus](https://user-images.githubusercontent.com/91793263/178230831-84412278-0e3a-4906-bc90-60b4c0d9e246.jpg)
