### ISSUE TITLE
Select default type search

### ISSUE THREAD

**Issue by acetaku** [elbowz/mobileMule#11]
Hi, elbowz.
I've seen that the default search type is Kad, but now I'm having issues trying to connect to Kad network and every time I search, I've to change the search type.
There would be the possibility of selecting the default search type from the configuration?
Thank you!

**Comment by elbowz** [comment]
Hi @acetaku,

 Global Search type stop working some times ago, so I have changed to Kad.

At this time you cannot change the default search type, but I guess implement it.

**Comment by Coll147** [comment]
Oh thanks, please implement it :)

**Comment by albertrodriguezdev** [comment]
Thank you for this solution!

**Comment by acetaku** [comment]
Thank you for this solution!

**Comment by elbowz** [comment]
In the latest release (v3.6.6b), I have introduced the requested features: 
mobileMule remembers your set type of search (ie. Local, Global, Kad).

@acetaku  remembers:
* clear you browser cache if you have some issues
* settings and configurations are saved locally in you browser, so changing pc/browser these are not preserved
* feel free to open a new issue if the problem persist
* ...and stars the project if you like it :)
