### ISSUE TITLE
Donation Package

### ISSUE THREAD

**Issue by Coll147** [elbowz/mobileMule#12]
I want to claim the donation package because I have donated :)
![Screenshot_20220709-171748_PayPal](https://user-images.githubusercontent.com/91793263/178115078-bb4e5776-186d-4ae2-8091-d66271689dca.png)
![Screenshot_20220709-184317_Drive](https://user-images.githubusercontent.com/91793263/178115080-bfec1b2f-1d20-4833-aaa3-3af2993c36f0.png)

**Comment by Coll147** [comment]
![Screenshot_20220709-184550_Chrome](https://user-images.githubusercontent.com/91793263/178115133-b6a20556-1334-4171-9432-2acbd96f2dc0.png)

**Comment by elbowz** [comment]
I have already unlocked the folder for your google account [aaroncoll147@gmail.com](mailto:aaroncoll147@gmail.com))...please stop spam, github an gdrive with message...and be patience
