### ISSUE TITLE
eMule compatible?

### ISSUE THREAD

**Issue by arithesage** [elbowz/mobileMule#13]
Hi, i started using aMule in my Kubuntu Server, but after experiencing super-low speeds i decided switching to eMule with Wine, where i experience a notable speed boost, so i would like to use this template with eMule, but i wonder if it would be compatible...

In case of not being compatible, could be possible to create a eMule version?

**Comment by elbowz** [comment]
Hi @ariaththesage, i did some speedy research, but eMule seems has a completely different templating engine and approach. 

So, mobileMule is not compatible with eMule and it will not ported, sorry.

I didn't know these performance  related issues, and never thought "emulation" with wine could improve the performance.
