### ISSUE TITLE
search not working (donation edition)

### ISSUE THREAD

**Issue by traycold** [elbowz/mobileMule#3]
Function search not working, it generates a JS error:
`ReferenceError: event is not defined[Learn More]  jquery.min.js%20line%202%20%3E%20eval:48:13
	<anonymous> http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js%20line%202%20%3E%20eval:48:13
	n.event.dispatch http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:3:6352
	n.event.add/r.handle http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:3:3162
	n.event.trigger http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:3:5510
	.trigger/< http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:3:11472
	.each http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:2:2878
	n.prototype.each http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:2:845
	.trigger http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:3:11451
	o http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.3/jquery.mobile.min.js:4:3513
	p http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.3/jquery.mobile.min.js:4:3596
	n.event.dispatch http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:3:6352
	n.event.add/r.handle http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js:3:3162`

**Comment by elbowz** [comment]
I can not reproduce the bug...

Could you post your mobileMule version and browser version?

Try to uninstall (remove the template/skin folder) and reinstall it.
Also try with another browser on desktop pc and/or mobile.
