### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by gipasoft** [elbowz/mobileMule#4]
Hi, I have installed mobileMule on my QNAP TS-460 on virtual host.

This is  the home page:

![mobilemule](https://cloud.githubusercontent.com/assets/1884550/21163198/eacbaf54-c191-11e6-8973-605633809aed.PNG)

In google inspector i see this errors:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery.min.js:4 GET http://192.168.1.132:8089/status-ajax.php 500 (Internal Server Error)
```
What's my error? How can set the amule ip, user and password?

Thank in advance for any suggestion!

**Comment by elbowz** [comment]
On my pc I have not this error...I have checked the source and the **jquery.min.js** is available on http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js

I don't know what you mean with
> How can set the amule ip, user and password?

I think this is not related to my skin

**Comment by gipasoft** [comment]
Ok I did not realize that this is a skin for amule webserver.
I installed as a standalone web application, I think that this is the problem!
