### ISSUE TITLE
Download list not showing

### ISSUE THREAD

**Issue by aculotarpa** [elbowz/mobileMule#5]
Hi, i'm using mobileMule-v3.2.0b-donation-package to control an aMule 2.3.2 instance on an OSMC powered Raspberry pi 3.

On the download page I can't see any files, regardless of the filter I chose.
In any other page, the global download speed is reported correctly.

Inspecting the download page I receive this error
```
SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 361 of the JSON data utils.js:1:520
    success utils.js:1
    jQuery 4
        j
        fireWith
        x
        b
```
Upload page works fine.
Same behaviour in Chrome Mac, Firefox Mac, Safari Mac, Chrome Android, Chrome Windows.

Here is a comparison screenshots with aMuleGUI connected to the same aMule instance.

<img width="1280" alt="Schermata 2019-06-01 alle 11 30 59" src="https://user-images.githubusercontent.com/21076287/58747044-bed98300-8465-11e9-9032-08162c23371a.png">

Thank you in advance!

**Comment by elbowz** [comment]
I think to know what happens...You should have some filenames in download list with " (double quote) or \ (backslash).

If this is the issue, you have to rename the file on AmuleGui (F2).

My apologies but unfortunately amule is very old software and don't allow me to snatize the strings (http://wiki.amule.org/wiki/AMuleWeb_PHP)

keep me updated

p.s. if not this the case, try to search some filenames with "strange" character (accented letters, symbols, etc...)

**Comment by aculotarpa** [comment]
I moved my temp folder and created a new one, then I added just one file with only letters, numbers and one point in the name.
Still nothing in download list and same error in browser console.

**Comment by elbowz** [comment]
ok, we have to made some debug...

Go to mobileMule Download page by Chrome (I see you use it):
1. Menu / More tools / Developer tools
2. Network tabs
3. Now you should see a list on bottom left, select downloads-ajax.php
4. and on the right Response (see my attached image)
5. Post the text you see: `{ 'downloads':...`

![Screenshot_20190602_095827](https://user-images.githubusercontent.com/1451484/58758542-00793500-851d-11e9-9782-9818bd1a7958.png)

**Comment by aculotarpa** [comment]
Here the Response
```
{ "downloads": { "count": 1, "list": [{"name": "ubuntu-18.04-desktop-amd64.iso", "short_name": "ubuntu-18.04-desktop-amd64.iso", "hash": "022A3C948653B7B0377D07D4B7475A40", "speed": "275,83 kb", "status": "Downloading", "prio": "High(auto)", "src_count": 12, "src_count_xfer": 6, "last_seen_complete": "seen completed", "status_complted_class": "downloading", "percentual_progress": 1,03, "size_done": "18,91 mb", "size": "1,79 gb"}]} }
```
The console error is
```
Uncaught SyntaxError: Unexpected number in JSON at position 385
    at JSON.parse (<anonymous>)
    at Object.success (utils.js:1)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at x (jquery.js:8264)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)
```
(Previous one was gathered in Firefox)

All Chrome Extensions disabled

**Comment by elbowz** [comment]
This is very strange...
Your amule(web) version use "," instead of "." for float number. 
This depend on local string set in `LC_NUMERIC`, but this on PHP...amule have a modded (reduced) version and I don't know where it get the float number formatting information.

Could you post your amule (and amuleweb version) you have installed and SO?!

Anyway, for fix this issue, open the `downloads-ajax.php` file, and substitution this:
```
        echo ', "status_complted_class": "' . StatusCompltedClass($file) . '", "percentual_progress": ' . $percentual_progress;

        echo ', "size_done": "' . CastToXBytes($file->size_done) . '", "size": "' . CastToXBytes($file->size) . '"';
```
with this:
```
        echo ', "status_complted_class": "' . StatusCompltedClass($file) . '", "percentual_progress": "' . $percentual_progress;

        echo '", "size_done": "' . CastToXBytes($file->size_done) . '", "size": "' . CastToXBytes($file->size) . '"';
```

I'll update the repository with fix ASAP (...if the fix works)

**Comment by aculotarpa** [comment]
It works!
Great job, thank you!

Anyway, my setup is a Raspberry pi 3 with
`OSMC 2019.05-2` https://osmc.tv/, a `Debian 9.9` derived mediacenter
with aMuleD installed via apt-get from standard Debian repository
`aMuleD 2.3.2 compiled with wxBase(GTK2) v3.0.2 and Boost 1.62 (OS: Linux)`
`amuleweb 2.3.2 compiled with wxBase(GTK2) v3.0.2 and Boost 1.62`
OS locales are all set to `it_IT.UTF-8`, including `LC_NUMERIC`
I hope this can be helpful.

Thank you again

**Comment by elbowz** [comment]
Thanks for the patience... :)
