### ISSUE TITLE
View shared files

### ISSUE THREAD

**Issue by zoraksss** [elbowz/mobileMule#7]
Hi,

Excelent template for mobile but I miss the possibility to see information of all shared files...number of requests, accepted,total uploaded,priority...

Is this possible with the donation package?

Thanks

**Comment by elbowz** [comment]
Hi @zoraksss !

I'm sorry but you'll not find the shared files section neither in the donation package.

Donation adds only this features/pages:
* Search
* Configurations
* Add ed2k
* MobileMule (allow to change themes, refresh and other stuff)

I think I can append it to TODO list, but the new section don't be ready really soon. 

Anyway really never thought that could be useful to someone that information (unless you are a releaser), in effect no one have never made this request. Can I ask you why you need it?

Ciao!

**Comment by zoraksss** [comment]
Hi,

Of course you can ask. I'm willing to share and mantain on the net some files that with time are becoming harder to obtain, mostly animated series for kids in catalan language.

For this matter, it's useful to know number of petitions, complet sources of the file,and to be able to modify priority.

Anyway, this can be done from PC with amulegui, sure, But it's always useful to have all the options mobile and your webskin is really complete and usable to the point that the only thing i would miss the complete PC gui is for this.

Thanks for your interest :)

**Comment by elbowz** [comment]
thanks for have satisfied my curiosity...It's a really good motivation (to preserve animated series for kids) !

> For this matter, it's useful to know number of petitions, complet sources of the file,and to be able to modify priority.  

You have to check if this feature are already possible with default web template of amule(web)...If think it's possible (if i remember well).

> Anyway, this can be done from PC with amulegui, sure, But it's always useful to have all the options mobile and your webskin is really complete and usable to the point that the only thing i would miss the complete PC gui is for this.

I keep this issue open, as I have said I think the time will be long, anyway I add the feature to TODO list.

Ciao!

**Comment by zoraksss** [comment]
Thanks!

**Comment by elbowz** [comment]
Hey @zoraksss could you make a request [here](https://drive.google.com/folderview?id=0BzaXzhTPJkC7SnpOVG11OF9ITlE&usp=sharing) 
...I'm sorry, but I don't have any way to contact you. Paypal doesn't allow to message you (strange).

**Comment by elbowz** [comment]
Hi @zoraksss, with a looong delay, I have added your request to the latest version of mobileMule v3.6.0 (a668f69577cee27b91301010a43eb12940eebbb1) 

Feel free to open a new issue if you have problem.
