### ISSUE TITLE
Donation editon

### ISSUE THREAD

**Issue by Coll147** [elbowz/mobileMule#9]
Hello, I would like to know how much is the donation that must be contributed to get the donation edition of mobilemule. Thanks :) (it would be nice to pass a discord user or something to get in touch more easily)
I am also interested if there is a web demo to test the donation editon.

**Comment by elbowz** [comment]
> Hello, I would like to know how much is the donation that must be contributed to get the donation edition of mobilemule. Thanks :)

Donation is free...so, It's up to you choose how much you want donate.

> (it would be nice to pass a discord user or something to get in touch more easily)

Do you mean a community on Discord? I think we don't have enough users.

> I am also interested if there is a web demo to test the donation editon.  

I'm sorry, you can only try (self host) the base version...the donation add some "page" (Search, Settings, Add ed2k, advanced settings)

**Comment by Coll147** [comment]
Ok, I already donantes in Google Drive I am aaroncoll147@gmail.com 
![Screenshot_20220709-171748_PayPal](https://user-images.githubusercontent.com/91793263/178111871-bf5615d8-568d-48a5-ba2d-7580d8ba2e09.png)

**Comment by elbowz** [comment]
thx
